name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: myspaceman/softhub-back
          stage: main
          yaml: |
            name: softhub-back
            app: node@16
            options:
              ports: 3000
              start: node main.js
              env:
                - name: PORT
                  secret: port
                - name: DB_HOST
                  secret: db_host
                - name: DB_PORT
                  secret: db_port
                - name: DB_USER
                  secret: db_user
                - name: DB_PW
                  secret: db_pw
                - name: DB_NAME
                  secret: db_name
                - name: AUTH_EMAIL_ADDRESS
                  secret: auth_email_address
                - name: AUTH_EMAIL_PW
                  secret: auth_email_pw
                - name: SESSION_KEY
                  secret: session_key
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}